apiVersion: v1
kind: Secret
metadata:
  name: my-backend-secrets
  namespace: leap-app
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongodb-service:27017/university-system"
  PORT: "5000"
  JWT_SECRET: dhsjkfhvjddskjfldhdh
  LINKEDIN_REDIRECT_URI: http://localhost:5173/auth/linkedin/callback
  LINKEDIN_CLIENT_SECRET: your-secret
  LINKEDIN_CLIENT_ID: your-id
  REACT_APP_API_URL: http://my-backend-app:5000
