---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: leap-app
spec:
  selector:
    app: my-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  type: NodePort